add code comments
project-flogo/catalystml-flogo pull request #139
Opened 2020-01-27 00:09 UTC by skothari-tibco

2020-01-30 16:13 UTC, abramvandergeest commented
I have added Matt and Frank for the review of documents to make sure it is what we are looking for,  The issue this is addressing is Issue https://github.com/project-flogo/catalystml-flogo/issues/62

2020-01-30 17:24 UTC, abramvandergeest approved these changes
LGTM.  Everything that is in it looks good.  I think @fm-tibco and @mellistibco should see if they think anything more should be in the documentation.  Thanks for doing this Samip!

2020-02-04 16:10 UTC, mellistibco approved these changes

2020-02-04 17:39 UTC, fm-tibco requested changes

2020-02-04 17:39 UTC, fm-tibco commented on action/api/api.go
> +//Initiliaize the action.
Take a look at https://blog.golang.org/godoc-documenting-go-code.  We should probably follow their conventions for the go doc.

It states:

> Notice this comment is a complete sentence that begins with the name of the element it describes. This important convention allows us to generate documentation in a variety of formats, from plain text to HTML to UNIX man pages, and makes it read better when tools truncate it for brevity, such as when they extract the first line or sentence.
>

2020-02-05 15:27 UTC, abramvandergeest approved these changes
LGTM

2020-02-11 19:38 UTC, fm-tibco approved these changes

2020-02-12 15:42 UTC, merged