initial checkin
project-flogo/catalystml-flogo pull request #17
Opened 2019-08-26 16:36 UTC by SteveNY-Tibco

Please review my operation modules

2019-08-26 20:12 UTC, skothari-tibco requested changes

2019-08-26 20:12 UTC, skothari-tibco commented on operations/cleaning/groupBy/operation.go
> +func init() {
You'll need to remove the init() function from the operations

2019-08-26 20:12 UTC, skothari-tibco commented on operations/cleaning/groupBy/go.mod
> +replace github.com/project-flogo/cml/operations/common => ../../common
You don't need this if you remove `go.mod` from common.

2019-08-26 21:03 UTC, skothari-tibco commented on operations/cleaning/groupBy/operation.go
> +	result, err = this.groupBy(in.Data.(map[string][]interface{}))
Can you change `this` to `opt` or `operation` ?

2019-08-26 21:03 UTC, skothari-tibco commented on operations/cleaning/join/metadata.go
> +func ToDataFrame(val interface{}) (interface{}, error) {
Isn't this unnecessary?

2019-08-26 21:03 UTC, skothari-tibco commented on operations/cleaning/join/operation.go
> +		in.Left.(map[string][]interface{}),
What if in.Left is of type `map[string]interface{}`, wouldn't this throw error ?

2019-08-27 14:30 UTC, abramvandergeest requested changes
So you have the function ToInterfaceArray in the common library, but you also define it again in the metadata.go file of both transpose and mean.  Could you just consolidate it down to the common library? Cheers

2019-08-27 17:00 UTC, abramvandergeest requested changes
Can you include a README of the style at "https://github.com/abramvandergeest/cml/blob/master/sample_README.MD" for each operation?  This is where you would include discussions like how axis behaves in mean.

2019-09-10 14:38 UTC, abramvandergeest commented
Looks good to me.

2019-09-10 14:39 UTC, abramvandergeest approved these changes
Looks good to me

2019-09-10 15:01 UTC, skothari-tibco approved these changes

2019-09-10 15:01 UTC, merged